### ISSUE TITLE
Please remove console.log from library

### ISSUE THREAD

**Issue by yahasa** [nodegin/tglib#13]
Please remove console.log from Client.js. In some cases it's an unexpected behaviour.

**Comment by nodegin** [comment]
Hi, sorry for delay. Can you explain what mean unexpected behavior?

**Comment by yahasa** [comment]
Hi, sorry I didn't explain the problem.
If I use external logging library all my logs controlled by looger. If some library use console it pollutes the screen. It's like uncatchable throw.
For example, then I use terminal UI ([https://github.com/chjj/blessed](https://github.com/chjj/blessed) on screenshot) it looks like:
![uncontrolled_log_example](https://user-images.githubusercontent.com/1448038/39465248-faa77e3c-4d2a-11e8-8642-1449dc4f4b77.png)
In your library just one direct console usage, and I think it's not so informative. I just comment line
```console.log('Current update is empty.')```
and it works fine.

Also it would be perfect to control `getInput` from outside the library (and get rid of inquirer dependency ~ 10Mb in node_modules), but it's another issue.

**Comment by nodegin** [comment]
Hello, the `Current update is empty. ` log is removed in the next release. For the `getInput` method do you have any nice idea?
