### ISSUE TITLE
How does one set TDLib binary path? I would let myself out but I cant close stuff D:

### ISSUE THREAD

**Issue by TorlanDelta** [nodegin/tglib#31]
Thread name is my question. This is not documented afaik, I don't want to mess with tglib source. I wanna know the proper way. Sorry if I missed it, I may have lost half my intelligence wrestling with endless installation errors xD 

Yes, I built it myself, yes I installed all dependencies, yes I acquired my api key and stuff. I just need to know where to specify a path. Also, should it be a path to td/build/release ?

Found https://github.com/nodegin/tglib/issues/2 , will try now, sorry for your trouble!

**Comment by nodegin** [comment]
I suppose this issue is resolved?
