### ISSUE TITLE
Search libtdjson in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by vitalyster** [nodegin/tglib#40]
Currently tglib assumes libtdjson is in current directory, but I have libtdjson installed system-wide. If i change [this](https://github.com/nodegin/tglib/blob/master/Client.js#L25) to `binaryPath: "libtdjson"` it works for me as expected but it will break existing behavior for current directory (Or it works if run `LD_LIBRARY_PATH=. node script.js`). Is it possible to search library in LD_LIBRARY_PATH (default for node-ffi) + current directory?

**Comment by nodegin** [comment]
What if you leave the binaryPath option alone?
By default tglib will use "libtdjson" in CWD, ffi can find the binary for
me.

2018年10月22日(月) 19:52 vitalyster <notifications@github.com>:

**Comment by vitalyster** [comment]
I'm not sure you understand the problem, I want to search in LD_LIBRARY_PATH, not in CWD

**Comment by vitalyster** [comment]
binaryPath moved to options, this is no more actual
