### ISSUE TITLE
Local Database

### ISSUE THREAD

**Issue by erfannf** [nodegin/tglib#41]
Hi
Does maintaining a local database of messages is supported in tglib?

```
//@use_chat_info_database If set to true, the library will maintain a cache of users, basic groups, supergroups, channels and secret chats. Implies use_file_database
--
//@use_message_database If set to true, the library will maintain a cache of chats and messages. Implies use_chat_info_database
```

[TDLib](https://github.com/tdlib/td/blob/6129ebf39439647e277e88d9d43a2f897ffee63c/td/generate/scheme/td_api.tl)

**Comment by nodegin** [comment]
Hi, all local databases are stored in local `__tglib__` folder. 

Also, you can checkout `Client.js` you see only `use_message_database ` was set to true.
