### ISSUE TITLE
Problem with getSupergroupMembers

### ISSUE THREAD

**Issue by mortezae** [nodegin/tglib#45]
the command getSupergroupMembers and many other getSupergroup* don't work for me.
It gives no details in error messages, just "Query timed out after 30 seconds."
I googled a lot about tdlib + getSupergroupMembers to find probable simillar problem but it seems nobody else had this problem before me. Also I checked sample codes from other languages and found no mistake in my code. Here it is:
```javascript
let chatMembers = await client.fetch({
      '@type': 'getSupergroupMembers',
      'supergroup_id': -1001304740402,
      'filter': null,
      'offset': 0,
      'limit': 20
    })
```
I'm using TDLib 1.3 on Linux. I updated tglib from 2.x to 3.0.1 but there in no difference.

**Comment by mortezae** [comment]
Just noticed that if I use this supergroup id in `getChat` command instead of `getSupergroupMembers` , then I get:
```json
{ '@type': 'chat',
  id: -1001304740402,
  type:
   { '@type': 'chatTypeSupergroup',
     supergroup_id: 1304740402,
     is_channel: false },
  title: ...
```
As you see chat.id lacks the -100 prefix that supergroup_id owns. Then I removed the prefix in my code snippet (getSupergroupMembers) and this time I got this error:

```json'{"@type":"error","code":6,"message":"Supergroup not found"}'```

**Comment by mortezae** [comment]
So I can use this:
```javascript
    let chatMembers = await client.fetch({
      '@type': 'searchChatMembers',
      'chat_id': chat,
      'filter': null,
      'limit': 20,
    })
```
and I do for now. But still don't know whats wrong with supergroup commands.

**Comment by mortezae** [comment]
It was my mistake, in getSupergroupMembers documentation it is explicitly clarified that:
> Can be used only if SupergroupFullInfo.can_get_members == true; additionally, administrator privileges may be required for some filters.

**Comment by nodegin** [comment]
@mortezae Nice find
