### ISSUE TITLE
asks for Authorization credential though given in code

### ISSUE THREAD

**Issue by mortezae** [nodegin/tglib#46]
I had many scripts with tglib and they were logged in accounts and was working perfectly. After months now I want to use them again but not are logged in nor can login! They prompt me with:
tglib.input.AuthorizationType
tglib.input.AuthorizationValue
But no response after entering them. I don't remember what is changed during this time that stop it from working. Could you guide me please to find the problem?
(I also registered a callback for td:getInput following readme but no difference)

**Comment by nodegin** [comment]
Are you upgrading tglib to v3.x?

tglib now support WebAssembly therefore the authentication was changed. See the new authentication flow in example:

https://github.com/nodegin/tglib/blob/master/examples/sendMessage.js

**Comment by nodegin** [comment]
If your code written in v2.x you can install instead to lock your version in order to stabelize your programs.

**Comment by mortezae** [comment]
Thank you, I downgraded and my personal problem solved.
